In [0]:
import pandas as pd
data=pd.read_csv('data_nom2.csv')

In [34]:
data['nom_3'].unique()

array(['Russia', nan, 'Canada', 'Finland', 'Costa Rica', 'China', 'India'],
      dtype=object)

In [0]:
objects=['Russia','Canada', 'Finland', 'Costa Rica', 'China', 'India']
array=np.zeros((36,1))
r='nom_3'
for x in range(len(data)-1):
  y=x+1
  if data[r][x]==objects[0] and data[r][y]==objects[0]:
    array[0]+=1
  if data[r][x]==objects[0] and data[r][y]==objects[1]:
    array[1]+=1
  if data[r][x]==objects[0] and data[r][y]==objects[2]:
    array[2]+=1
  if data[r][x]==objects[0] and data[r][y]==objects[3]:
    array[3]+=1
  if data[r][x]==objects[0] and data[r][y]==objects[4]:
    array[4]+=1
  if data[r][x]==objects[0] and data[r][y]==objects[5]:
    array[5]+=1


  if data[r][x]==objects[1] and data[r][y]==objects[0]:
    array[6]+=1
  if data[r][x]==objects[1] and data[r][y]==objects[1]:
    array[7]+=1
  if data[r][x]==objects[1] and data[r][y]==objects[2]:
    array[8]+=1
  if data[r][x]==objects[1] and data[r][y]==objects[3]:
    array[9]+=1
  if data[r][x]==objects[1] and data[r][y]==objects[4]:
    array[10]+=1
  if data[r][x]==objects[1] and data[r][y]==objects[5]:
    array[11]+=1
  
  if data[r][x]==objects[2] and data[r][y]==objects[0]:
    array[12]+=1
  if data[r][x]==objects[2] and data[r][y]==objects[1]:
    array[13]+=1
  if data[r][x]==objects[2] and data[r][y]==objects[2]:
    array[14]+=1
  if data[r][x]==objects[2] and data[r][y]==objects[3]:
    array[15]+=1
  if data[r][x]==objects[2] and data[r][y]==objects[4]:
    array[16]+=1
  if data[r][x]==objects[2] and data[r][y]==objects[5]:
    array[17]+=1
  
  if data[r][x]==objects[3] and data[r][y]==objects[0]:
    array[18]+=1
  if data[r][x]==objects[3] and data[r][y]==objects[1]:
    array[19]+=1
  if data[r][x]==objects[3] and data[r][y]==objects[2]:
    array[20]+=1
  if data[r][x]==objects[3] and data[r][y]==objects[3]:
    array[21]+=1
  if data[r][x]==objects[3] and data[r][y]==objects[4]:
    array[22]+=1
  if data[r][x]==objects[3] and data[r][y]==objects[5]:
    array[23]+=1
  
  if data[r][x]==objects[4] and data[r][y]==objects[0]:
    array[24]+=1
  if data[r][x]==objects[4] and data[r][y]==objects[1]:
    array[25]+=1
  if data[r][x]==objects[4] and data[r][y]==objects[2]:
    array[26]+=1
  if data[r][x]==objects[4] and data[r][y]==objects[3]:
    array[27]+=1
  if data[r][x]==objects[4] and data[r][y]==objects[4]:
    array[28]+=1
  if data[r][x]==objects[4] and data[r][y]==objects[5]:
    array[29]+=1
  
  if data[r][x]==objects[5] and data[r][y]==objects[0]:
    array[30]+=1
  if data[r][x]==objects[5] and data[r][y]==objects[1]:
    array[31]+=1
  if data[r][x]==objects[5] and data[r][y]==objects[2]:
    array[32]+=1
  if data[r][x]==objects[5] and data[r][y]==objects[3]:
    array[33]+=1
  if data[r][x]==objects[5] and data[r][y]==objects[4]:
    array[34]+=1
  if data[r][x]==objects[5] and data[r][y]==objects[5]:
    array[35]+=1

In [0]:
array2=array.copy()
j=0
for i in range(36):
  if i%6==0 and i!=0:
    j+=6
  array2[i]=array2[i]/np.sum(array[j:j+6])

In [37]:
array2[:6]

array([[0.20757348],
       [0.04519127],
       [0.17834674],
       [0.26146564],
       [0.02444167],
       [0.2829812 ]])

In [38]:
array2[6:12]

array([[0.20601627],
       [0.0452582 ],
       [0.18114955],
       [0.2601471 ],
       [0.02389384],
       [0.28353504]])

In [40]:
array2[12:18]

array([[0.20620609],
       [0.04482613],
       [0.18113736],
       [0.26119175],
       [0.02482238],
       [0.2818163 ]])

In [0]:
import random

In [45]:
for x in range(len(data)):
  if data[r][x] not in objects:
    y=random.random()
    if y<=array2[4]:
      data[r][x]=objects[4]
    if y<=array2[1] and y>array2[4]:
      data[r][x]=objects[1]
    if y<=array2[2] and y>array2[1]:
      data[r][x]=objects[2]
    if y<=array2[0] and y>array2[2]:
      data[r][x]=objects[0]
    if y<=array2[3] and y>array2[0]:
      data[r][x]=objects[3]
    if y>array2[3]:
      data[r][x]=objects[5]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.6/

In [46]:
data[r].unique()

array(['Russia', 'Costa Rica', 'Canada', 'Finland', 'China', 'India'],
      dtype=object)

In [0]:
data.to_csv('data_nom2.csv',index=False)

In [0]:
(data[r]).replace(objects[0],0,inplace=True,limit=len(data))
(data[r]).replace(objects[1],1,inplace=True,limit=len(data))
(data[r]).replace(objects[2],2,inplace=True,limit=len(data))
(data[r]).replace(objects[3],3,inplace=True,limit=len(data))
(data[r]).replace(objects[4],4,inplace=True,limit=len(data))
(data[r]).replace(objects[5],5,inplace=True,limit=len(data))

In [0]:
j=0
rs=[0,0,0,0,0,0]
for x in range(len(data)):
  if data['nom_1'][x] not in objects:
    y=random.random()
    if data['nom_1'][x-1]==objects[0]:
      rs=array2[0:6]
      if y<=rs[1]:
        data['nom_1'][x]=objects[1]
      if y<=rs[5] and y>rs[1]:
        data['nom_1'][x]=objects[5]
      if y<=rs[2] and y>rs[5]:
        data['nom_1'][x]=objects[2]
      if y<=rs[0] and y>rs[2]:
        data['nom_1'][x]=objects[0]
      if y<=rs[4] and y>rs[0]:
        data['nom_1'][x]=objects[4]
      if y>rs[3]:
        data['nom_1'][x]=objects[3]
    
    if data['nom_1'][x-1]==objects[1]:
      rs=array2[6:12]
      if y<=rs[1]:
        data['nom_1'][x]=objects[1]
      if y<=rs[5] and y>rs[1]:
        data['nom_1'][x]=objects[5]
      if y<=rs[2] and y>rs[5]:
        data['nom_1'][x]=objects[2]
      if y<=rs[0] and y>rs[2]:
        data['nom_1'][x]=objects[0]
      if y<=rs[4] and y>rs[0]:
        data['nom_1'][x]=objects[4]
      if y>rs[3]:
        data['nom_1'][x]=objects[3]
    
    if data['nom_1'][x-1]==objects[2]:
      rs=array2[12:18]
      if y<=rs[1]:
        data['nom_1'][x]=objects[1]
      if y<=rs[5] and y>rs[1]:
        data['nom_1'][x]=objects[5]
      if y<=rs[2] and y>rs[5]:
        data['nom_1'][x]=objects[2]
      if y<=rs[0] and y>rs[2]:
        data['nom_1'][x]=objects[0]
      if y<=rs[4] and y>rs[0]:
        data['nom_1'][x]=objects[4]
      if y>rs[3]:
        data['nom_1'][x]=objects[3]
    
    if data['nom_1'][x-1]==objects[3]:
      rs=array2[18:24]
      if y<=rs[1]:
        data['nom_1'][x]=objects[1]
      if y<=rs[5] and y>rs[1]:
        data['nom_1'][x]=objects[5]
      if y<=rs[2] and y>rs[5]:
        data['nom_1'][x]=objects[2]
      if y<=rs[0] and y>rs[2]:
        data['nom_1'][x]=objects[0]
      if y<=rs[4] and y>rs[0]:
        data['nom_1'][x]=objects[4]
      if y>rs[3]:
        data['nom_1'][x]=objects[3]
    
    if data['nom_1'][x-1]==objects[4]:
      rs=array2[24:30]
      if y<=rs[1]:
        data['nom_1'][x]=objects[1]
      if y<=rs[5] and y>rs[1]:
        data['nom_1'][x]=objects[5]
      if y<=rs[2] and y>rs[5]:
        data['nom_1'][x]=objects[2]
      if y<=rs[0] and y>rs[2]:
        data['nom_1'][x]=objects[0]
      if y<=rs[4] and y>rs[0]:
        data['nom_1'][x]=objects[4]
      if y>rs[3]:
        data['nom_1'][x]=objects[3]
    
    if data['nom_1'][x-1]==objects[5]:
      rs=array2[30:36]
      if y<=rs[1]:
        data['nom_1'][x]=objects[1]
      if y<=rs[5] and y>rs[1]:
        data['nom_1'][x]=objects[5]
      if y<=rs[2] and y>rs[5]:
        data['nom_1'][x]=objects[2]
      if y<=rs[0] and y>rs[2]:
        data['nom_1'][x]=objects[0]
      if y<=rs[4] and y>rs[0]:
        data['nom_1'][x]=objects[4]
      if y>rs[3]:
        data['nom_1'][x]=objects[3]